name: linting, testing, building
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  lint-format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build production project
        run: bun run prod

      - name: Lint TypeScript
        run: bun run lint:ts

      - name: Run unit tests
        run: bun run test:unit

      - name: build storybook
        run: bun run storybook:build

      - name: screenshot testing
        run: bun run test:ui:ci